### ISSUE TITLE
Deduplication

### ISSUE THREAD

**Issue by grinapo** [dop251/diskrsync#12]
I confess I am not fluent in go, so there's a bit of guesswork at hand.

If I observe correctly you calculate hashes for all blocks, so when transferring, you have all the hashes for all the blocks. 

Would it be possible for a _mismatched block_ to look up its hash in the hash table and **if it's there and it already exists on the target _only transfer the hash instead_ of the whole block**, basically using locally already existing data instead of transferring it?

I would use something like `--dedup` switch for that if you feel someone would *not* like to use it (as it may be CPU intensive, in exchange for less traffic).

I wouldn't try to write it unless absolutely necessary since it would require large amounts of time to familiarise with go, so it would take quite long for me.

**Comment by dop251** [comment]
I don't think it would provide much benefit. Because blocks are not aligned to a power of two the chances that any block would match are pretty slim. The only exception perhaps is when there are large areas of repeating non-zero bytes. However considering in most cases the transport is ssh which has compression enabled by default it's not worth the trouble.

**Comment by grinapo** [comment]
I wasn't aware that you don't use binary boundaries, you're right.

(Unfortunately this means that I have to write such a program from scratch (using binary boundaries and comparing hashes). I copy VM images which contain lots of repeated patterns [imagine like cloning an already present local image and then diffing the new one against it], but it's correct that they're better block-aligned. It'll be a great programming excercise anyway! Thanks!)
